### PR TITLE
Add first version of API docs

### PR DESCRIPTION
**Pull request by lpil**

### CODE REVIEW

**Comment by yonsaber** [comment]
Looks good to me, but for the Post object I think we will need to add an array of tags (or a comma separated list of tags) along with the author of the image. I'd like to have at least tagging in early so we can get filtering of content done out the gate.

**Comment by lpil** [comment]
I would much rather start very small and incrementally add features. I think there are many things to add before we can start to design tags such as user authentication, user authorization, post creation, image upload, image processing, etc.

For now I think it'd be a good goal to get these two read only endpoints up and have some DB seeds for populating the data.

**Comment by lpil** [comment]
Test

**Comment by lpil** [comment]
Basically I think the key to productivity here is to keep the items of work as small as possible :)

**Comment by yonsaber** [comment]
Sounds good to me, makes sense to get things in place esp things like auth then get the rest of the features up and running

**Comment by lpil** [comment]
Wanna give it a positive review if you're happy with it? :)

**Review by yonsaber — APPROVED** [review]
Clear outline of what is need and what each of the endpoints do

**Pull request merged**
